# Generated by Django 4.1.7 on 2024-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activation",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activation",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
