# Generated by Django 4.1.7 on 2024-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activation",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("loss", "Weight Loss"),
                    ("gain", "Weight Gain"),
                    ("maintain", "Weight Maintenance"),
                ],
                max_length=20,
            ),
        ),
    ]
