# Generated by Django 4.1.7 on 2024-08-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_activation_gender_activation_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
