# Generated by Django 4.1.7 on 2024-08-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_activation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("sedentary", "Sedentary: Little or no exercise"),
                    ("light", "Light: Exercise 1-3 times/week"),
                    ("moderate", "Moderate: Exercise 4-5 times/week"),
                    (
                        "active",
                        "Active: Daily exercise or intense exercise 3-4 times/week",
                    ),
                    ("very_active", "Very Active: Intense exercise 6-7 times/week"),
                ],
                default="sedentary",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activation",
            name="food_options",
            field=models.CharField(
                blank=True,
                choices=[("veg", "Veg"), ("non_veg", "Non-Veg")],
                max_length=10,
            ),
        ),
    ]
